version: '3'

services:
  guardian_api_pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USERNAME=guardian_user
      - POSTGRES_PASSWORD=guardian_password
      - POSTGRES_DATABASE=guardian_backend
